### ISSUE TITLE
Hitchance

### ISSUE THREAD

**Issue by Fedorito** [EternityX/DEADCELL-CSGO#10]
For me, hitchance works very bad. 
Someone have this problem?

**Comment by EternityX** [comment]
Any further information? It seems to be working fine for me

**Comment by Fedorito** [comment]
My ragebot just dont shoot when my hitchance > 20.

**Comment by t9z** [comment]
> My ragebot just dont shoot when my hitchance > 20.

Is it possible that you can post a screenshot of your current config? Works fine for me atleast.

**Comment by EternityX** [comment]
Or just export your settings and paste them here.

**Comment by medvedpvp** [comment]
experiencing the same problem, with hitchance > 20, the ragebot will only shoot while crouched :)

**Comment by EternityX** [comment]
> experiencing the same problem, with hitchance > 20, the ragebot will only shoot while crouched :)

I need more information.
Have you tried setting breakpoints on relevant variables and see if they are returning correct values?

Can you export your settings and paste them here?

**Comment by Fedorito** [comment]
> experiencing the same problem, with hitchance > 20, the ragebot will only shoot while crouched :)

I had same problem, but it fixed(?)
Sorry for my pEnglish
