### ISSUE TITLE
entity_listener not working

### ISSUE THREAD

**Issue by TXIuTnVsbA** [EternityX/DEADCELL-CSGO#100]
**Describe the bug**
entity_listener not working

**To Reproduce**
normal operation;

**Expected behavior**
Not

**Screenshots**
Not

**Additional context**
"entity_listener.cpp"

void c_custom_listener::on_entity_created(c_base_entity* ent)

{cc->m_class_id} always != CCSPlayer

so,its not working, i don't know how to fix

**Comment by alpine971** [comment]
what do you mean it’s not working, we use it for ragebot inside the cheat and it works fine

**Comment by TXIuTnVsbA** [comment]
> what do you mean it’s not working, we use it for ragebot inside the cheat and it works fine

yet,entity_listener is not working,

code:
```
client_class* cc = ent->get_client_class();
	if (!cc)
		return;

	switch (cc->m_class_id) {//its always != CCSPlayer
	case CCSPlayer: {

		m_players.emplace_back(ent_container_t(ent));

		break;
	}
	default:
		break;
	}
```

**Comment by alpine971** [comment]
what do you mean not working, are you calling the init function on cheat initialization?

**Comment by TXIuTnVsbA** [comment]
> what do you mean it’s not working, we use it for ragebot inside the cheat and it works fine

= =maybe i'm play the fake csgo now= =i'm so sorry for my broken English

`switch` its not work , ```cc->m_class_id ``` the m_class_id its always  not equal CCSPlayer(id: 38)
and ragebot,chams,its not work to

**Comment by alpine971** [comment]
pull the latest version and inject it, attach a debugger and put a breakpoint on the loop

**Comment by TXIuTnVsbA** [comment]
> pull the latest version and inject it, attach a debugger and put a breakpoint on the loop

so sorry ,its my bad,
now i know it.
when i inject before connected,its work.
but i inject it after connected,its not work.
