### ISSUE TITLE
crashes on regebot(std::sort)

### ISSUE THREAD

**Issue by TXIuTnVsbA** [EternityX/DEADCELL-CSGO#101]
**Describe the bug**
crashes on regebot

**To Reproduce**
when i enable ragebot

**Additional context**
the std::sort function
when 
_Right == _Left;
will be error;

**Screenshots**
![bug1](https://user-images.githubusercontent.com/26364656/56643909-33721280-66ad-11e9-8365-4e79c2a5396b.PNG)
![bug2](https://user-images.githubusercontent.com/26364656/56643937-44228880-66ad-11e9-8a28-72556d1b6a53.png)
![bug3](https://user-images.githubusercontent.com/26364656/56644235-e3e01680-66ad-11e9-8437-cb28987d2ea7.PNG)

**Comment by alpine971** [comment]
how does this happen only on your end what the fuck

**Comment by TXIuTnVsbA** [comment]
> how does this happen only on your end what the fuck

maybe my csgo client is different versions.
and my ide is,vs2019,
maybe is different  to.

well = = i fix it 
if left = right,i return false,
its simple fix,
but i don't think its right.

**Comment by danielkrupinski** [comment]
In order to fix this see https://github.com/danielkrupinski/DEADCELL-CSGO/commit/5ec90fc7d16a4049dae78e7ba3602f8ddb8d5361. I have submitted [PR with appropriate fix](https://github.com/EternityX/DEADCELL-CSGO/pull/104).

**Comment by TXIuTnVsbA** [comment]
> In order to fix this see [danielkrupinski@5ec90fc](https://github.com/danielkrupinski/DEADCELL-CSGO/commit/5ec90fc7d16a4049dae78e7ba3602f8ddb8d5361). I have submitted [PR with appropriate fix](https://github.com/EternityX/DEADCELL-CSGO/pull/104).

thanks!
