### ISSUE TITLE
[Question] Is it working after (30/4/2019)

### ISSUE THREAD

**Issue by Havoccboi** [EternityX/DEADCELL-CSGO#118]
Is this cheat updated? working after the latest csgo update?

**Comment by t9z** [comment]
https://github.com/EternityX/DEADCELL-CSGO/tree/update

The  **update** branch is being updated currently, not entirely sure if it's working or not. Since it's open source, you could update it yourself. Everything needed to update is in unknowncheats.me

**Comment by EternityX** [comment]
Update branch is not completely up-to-date yet.

**Comment by EternityX** [comment]
Main branch should be fully updated now. Let me know if you have any issues.
eb23d7a80663961aeae7f1fe5d485df9c6187834
