### ISSUE TITLE
Some possible code bugs

### ISSUE THREAD

**Issue by anarh1st47** [EternityX/DEADCELL-CSGO#122]
https://github.com/EternityX/DEADCELL-CSGO/blob/7f41efe34e52df1c5dceaf51dfd22b180e1a0769/deadcell/util/pattern/pattern.hpp#L40

">=" here?

https://github.com/EternityX/DEADCELL-CSGO/blob/cab17a8ba8af0bdb293ac78accc1286bb9fdfcf7/csgo/features/visuals/visuals.cpp#L467

This always should be false, maybe strcmp?

https://github.com/EternityX/DEADCELL-CSGO/blob/dfad88afa0b5b862d391c31116dcf1bb6ce99b91/deadcell/math/math.cpp#L110-L113

v.z  will always 1.f(not only in else state), probably use "," instead ";" here?

Also you're doing great staff guys by creating open source cheat, thank you!

**Comment by TXIuTnVsbA** [comment]
can you change it?
and Pull requests?

**Comment by alpine971** [comment]
Sorry for late response anarch1st, didn't pay attention to this, thanks for your feedback, feel free to make pr to fix the above mentioned issues.
