### ISSUE TITLE
Game crashing and debug brings me here

### ISSUE THREAD

**Issue by Captainminerz** [EternityX/DEADCELL-CSGO#125]
The game is crashing when i move the menu around sometimes and just out of nowhere. Both crashes lead to the same thing when i debug.

![image](https://user-images.githubusercontent.com/6278741/57812342-c3e6c480-773a-11e9-99c1-1baaeae605dc.png)

**Additional context**

Debugging tells me the error is at "control->CalculateAbsoluteLocation();"

**Comment by alpine971** [comment]
Use imgui instead, known issue with oshgui.

**Comment by Captainminerz** [comment]
Is imgui already in the cheat or no?

**Comment by alpine971** [comment]
imgui branch

**Comment by Captainminerz** [comment]
Alrighty i'll check it out, thanks for the feedback :)

**Comment by TXIuTnVsbA** [comment]
copy code in imgui,you try it
