### ISSUE TITLE
Game crashes/freezes on injection

### ISSUE THREAD

**Issue by Gubbi099** [EternityX/DEADCELL-CSGO#127]
Title says it all. The game just crashes/freezes when the dll is injected

**Comment by TXIuTnVsbA** [comment]
what ? gui? core? what?

**Comment by TXIuTnVsbA** [comment]
if you has crashes in 2nd inject,
you add memset(m_movedata) in engine_pred,i guess

**Comment by Gubbi099** [comment]
I am using the ImGui build of deadcell

**Comment by alpine971** [comment]
Can you attach a debugger and provide more info please.

**Comment by NetsuTheSkid** [comment]
gubbi its because you blocked me on discord @Gubbi099
