### ISSUE TITLE
address.h is full of UB

### ISSUE THREAD

**Issue by 18** [EternityX/DEADCELL-CSGO#129]
The entirety of address.h is full of undefined behavior. Casting the pointer to any pointer type other than the type of the object it points to, a base class thereof, `char` or `void*` will result in an UB as soon as it is dereferenced and used in a context that would access the pointed to objects value (say, an lvalue-to-rvalue conversion). See http://eel.is/c++draft/expr.reinterpret.cast#7 , http://eel.is/c++draft/expr.static.cast#13 , http://eel.is/c++draft/basic.compound#def:pointer-interconvertible and http://eel.is/c++draft/expr.prop#basic.lval-11

Also, force inlining is unnecessary. Member functions defined in the class they are declared in are implicitly inline, and the compiler does a better job of knowing when to inline.

**Comment by alpine971** [comment]
Thanks for the small write up, feel free to make a pr.
