### ISSUE TITLE
Community browser buggy

### ISSUE THREAD

**Issue by Captainminerz** [EternityX/DEADCELL-CSGO#130]
When i goto community browser after injecting, the actual browser will become like orange or invisible so i looks like it isnt there at all. Does anyone else have this error and/or a fix?

**Comment by EternityX** [comment]
This is an issue with the D3D9ex render states, I'd look there

**Comment by Captainminerz** [comment]
> This is an issue with the D3D9ex render states, I'd look there

Alrighty

**Comment by Captainminerz** [comment]
> This is an issue with the D3D9ex render states, I'd look there

Do you think i could just take out D3D9ex from the source?

**Comment by alpine971** [comment]
You can't take out D3D9Ex from the source, there's something wrong with the render states that makes community browser disappear.

**Comment by coconut24** [comment]
you can fix this by backing up vertex declaration and vert shader then restore it before calling original EndScene
http://prntscr.com/o26p2m

**Comment by alpine971** [comment]
> you can fix this by backing up vertex declaration and vert shader then restore it before calling original EndScene
> http://prntscr.com/o26p2m

would be awesome if you could make a pr :)
