### ISSUE TITLE
hitbox bug (sv_showlagcompensation)

### ISSUE THREAD

**Issue by TXIuTnVsbA** [EternityX/DEADCELL-CSGO#133]
when i used  this (this has some problem):
```
float mod = bbox->m_flRadius != -1.f ? bbox->m_flRadius : 0.f;
math::vector_transform(bbox->bb_min - mod, matrix[bbox->bone_index], min);
math::vector_transform(bbox->bb_max + mod, matrix[bbox->bone_index], max);
```

![20190604041843_1](https://user-images.githubusercontent.com/26364656/58831791-0fc4c380-8680-11e9-8e46-1dcd395ee139.jpg)

=========================================================
but when i used  this (this has not problem)
this is old code from "deadcell":

```
math::vector_transform(bbox->bb_min, matrix[bbox->bone_index], min);
math::vector_transform(bbox->bb_max, matrix[bbox->bone_index], max);
```

![20190604041747_1](https://user-images.githubusercontent.com/26364656/58831812-1d7a4900-8680-11e9-8ad7-194a9c1fafa3.jpg)

**Comment by alpine971** [comment]
so whats the problem?, not our problem that you pasted something that you have to clue about.

**Comment by TXIuTnVsbA** [comment]
> so whats the problem?, not our problem that you pasted something that you have to clue about.

no！not my problem!

see here:
https://github.com/EternityX/DEADCELL-CSGO/issues/102

**Comment by alpine971** [comment]
Bruh, you used code that's not supposed to be used for drawing hitboxes

**Comment by TXIuTnVsbA** [comment]
> you used code that's not supposed to be used for drawing hitboxes

i used command "sv_showlagcompensation".

i'm not used for drawing hitboxes, i'm used for the ragebot, but sometime i can't hit anyone

but how to draw hitboxes? Client Hitboxes (code) ?
