### ISSUE TITLE
Backtrack log bombs the performance

### ISSUE THREAD

**Issue by aurismat** [EternityX/DEADCELL-CSGO#134]
**Describe the bug**
in backtrack.cpp: lines 175-176
`g_notify.add( true, OSHColor::FromARGB( 220, 249, 44, 69 ), "fired shot at backtrack record ( player %s, %i ticks, %i choked ).",
e->get_info( ).m_player_name, cmd->m_tick_count - TIME_TO_TICKS( corrected_simtime ), ticks_choked );`

After I commented those lines out, the FPS drops while using aim stopped.

**To Reproduce**
Just run the cheat with 0% hitchance(i know, unrealistic). once the aimbot goes ham, the log should bomb the FPS.

**Expected behavior**
That shouldn't destroy your FPS, but maybe my PC is a total potato, idk/idc.

**Additional context**
I'd say adding a toggle to this should fix the issue.

**Comment by TXIuTnVsbA** [comment]
I commented it out.

**Comment by alpine971** [comment]
Can you possibly provide more information?, run the performance profiler on visual studio while debugging, should give you a clear representation of whats eating up the performance.
