### ISSUE TITLE
(master branch) Game Crashes/"Freezes" on inject 

### ISSUE THREAD

**Issue by dagadtwok** [EternityX/DEADCELL-CSGO#138]
Injecting with native injection does nothing. The game just freeze(?), cant alt+tab back.  VS debug gives nothing back. (The process is still running, but cant alt+tab back)
`The thread 0x844 has exited with code 0 (0x0).
The thread 0x2b44 has exited with code 0 (0x0).
The thread 0x3664 has exited with code 0 (0x0).
The thread 0x2094 has exited with code 0 (0x0).
`
Injecting with manual mapping makes the game crashes
![2019-06-16--16-56-24](https://user-images.githubusercontent.com/41807270/59565120-6e5e4a00-904f-11e9-9c4c-d8893318ae3d.png)

Probably im a retard but idk.

**Comment by BroniDanson** [comment]
Unfortunately, its the manual mapping injection that crashes it, I tough I done something wrong too but it's just how this cheat is coded

**Comment by Jacellen** [comment]
After injection, the game does not unfold

**Comment by dagadtwok** [comment]
With the newest commit now works. (Only with native inject)
