### ISSUE TITLE
Aimstep casual

### ISSUE THREAD

**Issue by Jacellen** [EternityX/DEADCELL-CSGO#140]
Will the feature be implemented Aimstep for public servers?

**Comment by packetSent** [comment]
This is not a legit cheat...

**Comment by EternityX** [comment]
> This is not a legit cheat...

And aim step isn't a legit feature...

**Comment by jdb-jdb** [comment]
After a fresh compilation of the source here(no modifications to code and no settings switched on in the menu) once I inject every weapon fires correctly and all grenades fire etc etc. However, all-pistols including the cz75 don't fire, I click the button and nothing happens. I have made sure no other key except weapon firing is bound to mouse click 1 but the other weapons fire correctly so I wouldn't think it would be this. I've included a video of exactly what happens
[Here's the video](https://verystream.com/stream/UV3DnyiyiFf/2019-08-02_17-50-20.flv)
