### ISSUE TITLE
SetupBones meme

### ISSUE THREAD

**Issue by pidorawka** [EternityX/DEADCELL-CSGO#141]
I'm really-really interested in how overwriting entity id supposed to fix setupbones for you? It's not a """magic""" value.
https://github.com/EternityX/DEADCELL-CSGO/blob/master/csgo/hooking/hooks/SetupBones.cpp#L28

**Comment by alpine971** [comment]
ask xxharcs, the setupbones code belongs to him, setupbones function hook is commented out anyways

**Comment by pidorawka** [comment]
the fuck lmao
