### ISSUE TITLE
Pistols don't fire

### ISSUE THREAD

**Issue by ghost** [EternityX/DEADCELL-CSGO#142]
After a fresh compilation of the source here(no modifications to code and no settings switched on in the menu) once I inject every weapon fires correctly and all grenades fire etc etc. However, all-pistols including the cz75 don't fire, I click the button and nothing happens. I have made sure no other key except weapon firing is bound to mouse click 1 but the other weapons fire correctly so I wouldn't think it would be this. I've included a video of exactly what happens
[Here's the video](https://verystream.com/stream/UV3DnyiyiFf/2019-08-02_17-50-20.flv)

**Comment by alpine971** [comment]
Most of us quit csgo cheat dev, I think it’s pretty obvious, we’ll help sometimes, but I don’t think you should use the cheat, cheat has some really nice code in it that youcan hopefully learn from, as to the issue, it’s probably related to automatic weapons

**Comment by rraggerr** [comment]
probably because this
https://github.com/EternityX/DEADCELL-CSGO/blob/a2eb4eb9099b1ccdfe9b40e67a96547aaecdd376/csgo/features/misc/misc.cpp#L36
