### ISSUE TITLE
Crashes when I join a match

### ISSUE THREAD

**Issue by RandomPerson23521** [EternityX/DEADCELL-CSGO#147]
I compile the cheat, inject the dc-csgo.dll.
Cheat loads perfectly, but when I try to join any game, offline with bots, casual, it crashes.

**To Reproduce**
1- Compile
2- Inject
3- Join any game

**Expected behavior**
I expected to be able to play without the game crashing.

I would like to fix this as soon as possible, as I really wanna try out this cheat.
I'm compiling with Release x86 with SDK 10.0.17134.0
And Visual Studio 2017 (v141)

**Comment by EternityX** [comment]
It's outdated, you'll likely need to update the virtual indices

**Comment by InsDel2113** [comment]
Check my PR, has updated indexes.

**Comment by priveight02** [comment]
@EternityX https://i.imgur.com/JrRh269.png how to fix this error ?

**Comment by EternityX** [comment]
update the virtual indices

**Comment by priveight02** [comment]
@EternityX ok, but how to do that x)

**Comment by priveight02** [comment]
@EternityX could you just fix it plss it would be great

**Comment by auth12** [comment]
Fixed.
