### ISSUE TITLE
Crash on joining game

### ISSUE THREAD

**Issue by EricSmith17** [EternityX/DEADCELL-CSGO#149]
pls update

**Comment by EricSmith17** [comment]
can you fucking respond please ? :(

**Comment by rraggerr** [comment]
do it yourself

**Comment by EricSmith17** [comment]
Please help me, i updated indexes like accuracy, spread, VPHysics post think sig, is_player, etc. can you please list me here what i need to update ? ;(

**Comment by luk1337** [comment]
do you really expect that people would be willing to help you after that:
![image](https://user-images.githubusercontent.com/6830979/67641583-34f1f100-f903-11e9-9159-4ea3155547b8.png)

**Comment by EricSmith17** [comment]
sorry people for my bad england

**Comment by luk1337** [comment]
Well i guess you are out of options. No cheat for you then~

**Comment by EricSmith17** [comment]
youre useless as VAC

**Comment by luk1337** [comment]
ok

**Comment by EricSmith17** [comment]
im pretty sure that you didnt even have anything updated yourself

**Comment by luk1337** [comment]
I don't even use it. I contributed once and that's about it.
I could probably figure out what to do if I cared enough.

**Comment by EricSmith17** [comment]
yes but youre not going to help me yes ?

**Comment by luk1337** [comment]
exactly!

**Comment by EricSmith17** [comment]
fuck you

**Comment by EricSmith17** [comment]
what the fuck is "virtual indices" ? that mean like some virtual function that is equal to zero ( virtual shit(vector origin) = 0 )
?
