### ISSUE TITLE
just asking

### ISSUE THREAD

**Issue by xsincbt** [EternityX/DEADCELL-CSGO#150]
is it better to use vs 2017 for this cheat or 2019 is fine for this

**Comment by EternityX** [comment]
Project works out of the box with 2019

**Comment by itzshahay** [comment]
```
Project works out of the box with 2019
```
What a lie @EternityX

**Comment by EternityX** [comment]
> ```
> Project works out of the box with 2019
> ```
> 
> What a lie @EternityX

Try the main branch.
I've never used the imgui branch.
