### ISSUE TITLE
wont build imgui version

### ISSUE THREAD

**Issue by itzshahay** [EternityX/DEADCELL-CSGO#152]
**Describe the bug**
Doesn't let me build the ImGui version

**To Reproduce**
Hell, I don't know?

**Expected behavior**
a build to dll, kthx

**Screenshots**
http://prntscr.com/q43ycv

**Additional context**
well i just tried building this,
i've tried different build configurations, yet this doesnt do anything

**Comment by itzshahay** [comment]
Also,
http://prntscr.com/q4415a
in general, this is very weird and exceptionally confusing.
Precompiled headers are enabled

**Comment by EternityX** [comment]
If you're unable to fix this, I don't recommend using this project

**Comment by itzshahay** [comment]
@EternityX There was a fix, downgrading from 2019 to 2017 using v141 toolset did the job, I just thought deadcell as being a out-of-the-box 2019 version
