### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Quois** [EternityX/DEADCELL-CSGO#153]
So I'm crashing as soon as I join a game, which I'm sure is because of it being outdated. I could not find any defined offsets in the source code though. Where do I find those? Thanks.

**Comment by sdkabuser** [comment]
Hi, sorry for the late response. The offsets are automatically found through a netvar manager and are not predefined within the source. I believe the cause of your crashing is an incorrect index for a virtual function or some other code in your project that is causing issues such as accessing memory from a null pointer or dividing by zero. 

Kind Regards, sdk abuser.

**Comment by auth12** [comment]
Fixed.
