### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by peopu** [EternityX/DEADCELL-CSGO#157]
**Each time I have 2 errors when compiling**

![image](https://user-images.githubusercontent.com/53833371/80237599-48d1a200-865d-11ea-96a7-af43eddb6551.png)

pls help ;c

**Comment by alpine971** [comment]
In the includes, rename #include <experimental/filesystem> to just #include <filesystem>

**Comment by peopu** [comment]
what to do now? 
![image](https://user-images.githubusercontent.com/53833371/80239913-4ffaaf00-8661-11ea-8cfa-b8f8d3e2f085.png)

**Comment by alpine971** [comment]
rename every instance of std::experimental::filesystem to std::filesystem

**Comment by peopu** [comment]
now i have it
![image](https://user-images.githubusercontent.com/53833371/80241285-a0730c00-8663-11ea-83a4-a0e76e365c3c.png)

**Comment by alpine971** [comment]
go to config.cpp and menu.cpp and remove the experimental/ part of the include

**Comment by peopu** [comment]
![image](https://user-images.githubusercontent.com/53833371/80241616-3149e780-8664-11ea-9e1f-484cf07fa1f3.png)

**Comment by alpine971** [comment]
double click on the first menu.cpp error show me what you did

**Comment by peopu** [comment]
![image](https://user-images.githubusercontent.com/53833371/80242048-f98f6f80-8664-11ea-888f-f053d2c4aba8.png)

**Comment by alpine971** [comment]
remove ::filesystem once

**Comment by peopu** [comment]
![image](https://user-images.githubusercontent.com/53833371/80242373-8fc39580-8665-11ea-9d4d-0052e93fe2b9.png)

**Comment by alpine971** [comment]
make sure you set c++ version properly in the project settings and #include <filesystem> properly

**Comment by peopu** [comment]
i just run sln file i wanna compile and got this

**Comment by alpine971** [comment]
I understand but the project isn’t recommended to people with no knowledge of c++, deadcell is unfortunately still in development and isnt a finished product.

**Comment by peopu** [comment]
I understand thx for help
