### ISSUE TITLE
Cannot Build, 50 Errors on the Log

### ISSUE THREAD

**Issue by Talithaald** [EternityX/DEADCELL-CSGO#159]
1>------ Build started: Project: oshgui lib, Configuration: Release Win32 ------
1>Direct3D9ExRenderer.cpp
1>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\oshgui\Drawing\Direct3D9\Direct3D9GeometryBuffer.hpp(14,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>Direct3D9ExTexture.cpp
1>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\oshgui\Drawing\Direct3D9Ex\Direct3D9ExTexture.cpp(3,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>Direct3D9GeometryBuffer.cpp
1>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\oshgui\Drawing\Direct3D9\Direct3D9GeometryBuffer.hpp(14,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>Direct3D9Renderer.cpp
1>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\oshgui\Drawing\Direct3D9\Direct3D9GeometryBuffer.hpp(14,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>Direct3D9Texture.cpp
1>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\oshgui\Drawing\Direct3D9\Direct3D9Texture.cpp(4,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>Direct3D9TextureTarget.cpp
1>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\oshgui\Drawing\Direct3D9\Direct3D9GeometryBuffer.hpp(14,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>Direct3D9ViewportTarget.cpp
1>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\oshgui\Drawing\Direct3D9\Direct3D9GeometryBuffer.hpp(14,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>Done building project "OSHGui_StaticLibrary.vcxproj" -- FAILED.
2>------ Build started: Project: dc-csgo, Configuration: Release Win32 ------
2>chai_wrapper.cpp
2>ent_listener.cpp
2>configs.cpp
2>dllmain.cpp
2>anim.cpp
2>antiaim.cpp
2>autowall.cpp
2>chams.cpp
2>engine_pred.cpp
2>events.cpp
2>fakelag.cpp
2>geometry.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\chaiscript\chai_wrapper.cpp)
2>misc.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\dllmain.cpp)
2>nade_pred.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\anti-aim\antiaim.cpp)
2>notifications.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\entity listener\ent_listener.cpp)
2>backtrack.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\events\events.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\chams\chams.cpp)
2>ragebot.cpp
2>resolver.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\fakelag\fakelag.cpp)
2>visuals.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\autowall\autowall.cpp)
2>CreateMove.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\geometry\geometry.cpp)
2>DoExtraBonesProcessing.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\animations\anim.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\configs\configs.cpp)
2>DoPostScreenSpaceEffects.cpp
2>DrawModelExecute.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\engine_pred\engine_pred.cpp)
2>EndScene.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\misc\misc.cpp)
2>GetMaterial.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\nade_pred\nade_pred.cpp)
2>FrameStageNotify.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\notifications\notifications.cpp)
2>GetViewmodelFOV.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\backtrack\backtrack.cpp)
2>IsHltv.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\resolver\resolver.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\visuals\visuals.cpp)
2>LevelShutdown.cpp
2>LevelInitPostEntity.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\features\ragebot\ragebot.cpp)
2>LockCursor.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\CreateMove.cpp)
2>OverrideView.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\DoExtraBonesProcessing.cpp)
2>PaintTraverse.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\GetMaterial.cpp)
2>Present.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\FrameStageNotify.cpp)
2>RenderSmokeOverlay.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\EndScene.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\DoPostScreenSpaceEffects.cpp)
2>Reset.cpp
2>ResetEx.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\GetViewmodelFOV.cpp)
2>SceneEnd.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\DrawModelExecute.cpp)
2>SetupBones.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\IsHltv.cpp)
2>ShouldDrawFog.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\LevelShutdown.cpp)
2>manager.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\LevelInitPostEntity.cpp)
2>menu.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\LockCursor.cpp)
2>DrawSetColor.cpp
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\OverrideView.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\Present.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\SceneEnd.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\RenderSmokeOverlay.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\ShouldDrawFog.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\PaintTraverse.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\Reset.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\SetupBones.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\hooks\ResetEx.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\hooking\manager.cpp)
2>C:\Users\ACER\Downloads\Compressed\DEADCELL-CSGO-master\DEADCELL-CSGO-master\csgo\inc.h(30,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file csgo\menu\menu.cpp)

**Comment by alpine971** [comment]
Install directx 9 SDK
