### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HackerGeo-sp1ne** [EternityX/DEADCELL-CSGO#161]
![image](https://user-images.githubusercontent.com/42976769/81481115-5af33900-9236-11ea-84a3-d070bd05cc9d.png)
how to fix this?

**Comment by alpine971** [comment]
Read the error message

**Comment by HackerGeo-sp1ne** [comment]
> Read the error message

yes but i dont know how to solve this

**Comment by OBO-1** [comment]
bruh
