### ISSUE TITLE
Build Error (Visual Studio 2019)

### ISSUE THREAD

**Issue by GodlyTM** [EternityX/DEADCELL-CSGO#164]
**Describe the bug**
Hi so when building deadcell i get a error with this line "#include <experimental::filesystem> and it wont build please try to fix it or tell me how i can fix it Thank you

**To Reproduce**
Try to build using the most updated visual studio (If this is for real the problem i will install visual studio 2017 just tell me

**Expected behavior**
I expected it to build correctly 

**Screenshots**
i already deleted it for now sorry but i think you can get what kinda error that would look like

**Additional context**
i dont really have anything else

**Comment by alpine971** [comment]
you should do #include <filesystem> insteaf of whatever you have there

**Comment by OBO-1** [comment]
use 2017 SDK instead of whatever u use
