### ISSUE TITLE
Injection crash/Error pop-up

### ISSUE THREAD

**Issue by ekstazas** [EternityX/DEADCELL-CSGO#167]
**Describe the bug**
upon injecting, csgo crashes and a small window with the error message pops up:
"Failed to initialize interfaces"

**To Reproduce**
Steps to reproduce the behavior.
just inject (error happened on 2020-06-09)

**Expected behavior**
the cheat to work, open menu etc.

**Screenshots**
https://imgur.com/xinnLnw

**Additional context**
no

**Comment by atheleon** [comment]
Update client_panorama.dll to client.dll

**Comment by mikkhimself** [comment]
@atheleon This does fix the popup issue indeed, any direction in updating structs?

**Comment by mikkhimself** [comment]
```static auto PostThinkVPhysics = pattern::find< bool(__thiscall*)(c_base_entity*) >(g_csgo.m_client_dll, "55 8B EC 83 E4 F8 81 EC ?? ?? ?? ?? 53 8B D9");
	static auto SimulatePlayerSimulatedEntities = pattern::find< void(__thiscall*)(c_base_entity*) >(g_csgo.m_client_dll, "56 8B F1 57 8B BE ?? ?? ?? ?? 83 EF 01");```

**Comment by mikkhimself** [comment]
```c++ int c_engine_pred::post_think(c_base_player* player) const {
	static auto PostThinkVPhysics = pattern::find< bool(__thiscall*)(c_base_entity*) >(g_csgo.m_client_dll, "55 8B EC 83 E4 F8 81 EC ?? ?? ?? ?? 53 8B D9");
	static auto SimulatePlayerSimulatedEntities = pattern::find< void(__thiscall*)(c_base_entity*) >(g_csgo.m_client_dll, "56 8B F1 57 8B BE ?? ?? ?? ?? 83 EF 01");```

**Comment by mikkhimself** [comment]
This works well, and doesn't make the game crash anymore, however the aimbot doesn't seem to shoot at all, can this be due to outdated offsets?

**Comment by alpine971** [comment]
> This works well, and doesn't make the game crash anymore, however the aimbot doesn't seem to shoot at all, can this be due to outdated offsets?

Possibly offsets, check hardcoded offsets in player class, and update vtable indexes.

**Comment by auth12** [comment]
Fixed.
