### ISSUE TITLE
issue with a .h file

### ISSUE THREAD

**Issue by Unverifieds** [EternityX/DEADCELL-CSGO#172]
here is an image of what it looks like
https://images-ext-1.discordapp.net/external/IsOrGyFNlBNJFlk_v4DRovBCBT-0EjP9wwSFhAK25nQ/https/cdn.serpent.wtf/uploads/x7213ao5.png
i have no idea why it says that, but idk how to fix it

**Comment by Unverifieds** [comment]
nvm fixed it

**Comment by InsDel2113** [comment]
> nvm fixed it

close the issue
