### ISSUE TITLE
stuck on "initializing deadcell." in debug after injecting

### ISSUE THREAD

**Issue by glibss** [EternityX/DEADCELL-CSGO#173]
Describe the bug A clear and concise description of what the bug is.
after injecting using extreme injector, the debug window will appear with the words "initializing deadcell." and nothing else happens, pressing insert does nothing.

To Reproduce Steps to reproduce the behavior.
build, and inject.

Expected behavior A clear and concise description of what you expected to happen.
expected to fully inject

Screenshots If applicable, add screenshots to help explain your problem.
n/a

Additional context Add any other context about the problem here.
n/a

**Comment by auth12** [comment]
Try with latest.
