### ISSUE TITLE
Control.cpp crash on injection

### ISSUE THREAD

**Issue by notfluorine** [EternityX/DEADCELL-CSGO#174]
**Describe the bug**
crash on injection 

**To Reproduce**
Steps to reproduce the behavior.
compile & inject

**Expected behavior**
inject

**Screenshots**
![ss](https://user-images.githubusercontent.com/25553209/88714958-28453800-d0e3-11ea-87a5-331842a7af45.png)

**Additional context**
happens with multicore rendering enabled and disabled

**Comment by auth12** [comment]
Fixed.
