### ISSUE TITLE
CSGO Crashing when I inject the DLL

### ISSUE THREAD

**Issue by Wilson732** [EternityX/DEADCELL-CSGO#178]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SquidmarcHD** [comment]
After i inject the cheat it just closes csgo instantly

**Comment by Cozythecoder** [comment]
@SquidmarcHD i think it because of the csgo update . you can fix it here https://www.unknowncheats.me/forum/counterstrike-global-offensive/310246-updates-megathread-64.html

**Comment by EternityX** [comment]
The repo is not updated to support the latest version of CS:GO. You will need to update any outdated offsets/patterns yourself.
