### ISSUE TITLE
Unable to start program - not a valid win32 application

### ISSUE THREAD

**Issue by Timmo5** [EternityX/DEADCELL-CSGO#182]
When I try compiling the cheat I get this error saying it's not a valid win32 application. What do I do?
![download (1)](https://user-images.githubusercontent.com/46894223/95901024-04fd6100-0d93-11eb-964f-e9cad6c940ab.png)
![download](https://user-images.githubusercontent.com/46894223/95901025-0595f780-0d93-11eb-92ea-c9ae4a95bf38.png)

**Comment by EternityX** [comment]
You need a DLL injector to use the binaries that are built.

**Comment by RXVAN** [comment]
> You need a DLL injector to use the binaries that are built.

thats uhm not what he was asking -_o

> When I try compiling the cheat
nothing to do with using it.

anyway, @Timmo5 you should use release build and make sure the lib files are included properly

**Comment by cleanin** [comment]
This is literally intended functionality for Visual Studio, Chances are you pressed F5 which is debug and run and VS tried to execute the .lib file which is obviously not an Win32 executable. Inject the DLL in the output directory.

**Comment by EternityX** [comment]
> > You need a DLL injector to use the binaries that are built.
> 
> thats uhm not what he was asking -_o
> 
> > When I try compiling the cheat
> 
> nothing to do with using it.
> 
> anyway, @Timmo5 you should use release build and make sure the lib files are included properly

Um, yes it is. He is trying to run the library by pressing F5 or clicking the 'Local Windows Debugger' button.

**Comment by Timmo5** [comment]
So what exactly is the problem? I think that it doesn’t work because my machine is x64 and the cheat is x86?

**Comment by calebbalboni17** [comment]
you cant open a DLL you need an injector I recommend using cs ghost or process hacker those seem to be the most consistent and work the best. You can find the download for them on cheater.run under the injector directory

**Comment by calebbalboni17** [comment]
> So what exactly is the problem? I think that it doesn’t work because my machine is x64 and the cheat is x86?
x86 includes x64 and x32 its able to run both of these programs just use an injector don't open a dll that does not work

**Comment by calebbalboni17** [comment]
> When I try compiling the cheat I get this error saying it's not a valid win32 application. What do I do?
> ![download (1)](https://user-images.githubusercontent.com/46894223/95901024-04fd6100-0d93-11eb-964f-e9cad6c940ab.png)
> ![download](https://user-images.githubusercontent.com/46894223/95901025-0595f780-0d93-11eb-92ea-c9ae4a95bf38.png)

wait a second I just realized ur issue u didn't put it on release don't have it on debug change it to release that might fix ur issue
