### ISSUE TITLE
i got 200 errors while building i have vs 2019 

### ISSUE THREAD

**Issue by saad977-ai** [EternityX/DEADCELL-CSGO#186]
i got 200 errors while building i have vs 2019 i dont know what i am missing

**Comment by SizeableNayNay** [comment]
Hi, I came across this issue as well. If you change the projects settings (not the solution's properties) in Properties, Configuration Properties, C/C++ / Languages / C++ Language Standard from Preview or default to ISO C++ 17 Standard etc. I hope this helps.
![image](https://user-images.githubusercontent.com/72110957/102690329-90182e80-41fc-11eb-9181-c29118f96f95.png)

**Comment by saad977-ai** [comment]
can u add me at discord Saad#1594 and help me ?

**Comment by software-engineer0** [comment]
> can u add me at discord Saad#1594 and help me ?
> 
> 

no

**Comment by saad977-ai** [comment]
why :/

**Comment by software-engineer0** [comment]
read the readme. useless post, have a nice day.
