### ISSUE TITLE
400 error still after trying someones fix

### ISSUE THREAD

**Issue by saad977-ai** [EternityX/DEADCELL-CSGO#187]
Severity	Code	Description	Project	File	Line	Suppression State
Message		see declaration of 'std'	deadcell	E:\vs\VC\Tools\MSVC\14.28.29333\include\deque	24	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2838	'Application': illegal qualified name in member declaration	deadcell	C:\Users\SaaduPc\Desktop\DEADCELL-CSGO-master\deadcell\input\input.hpp	13	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	deadcell	C:\Users\SaaduPc\Desktop\DEADCELL-CSGO-master\deadcell\input\input.cpp	23	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'string_view': is not a member of 'std'	deadcell	C:\Users\SaaduPc\Desktop\DEADCELL-CSGO-master\deadcell\console\console.hpp	23	

I AM NEW TO PASTING PLEASE HELP ME FIX ERROR OR TELL ME WHAT I AM MISSING

**Comment by software-engineer0** [comment]
the readme clearly states this wouldn't be the project for you. have a nice day. eternity please close this.

**Comment by saad977-ai** [comment]
whyyyyyyyyyyyyyyy

**Comment by saad977-ai** [comment]
just help meeeeeeeeeeeeeeeeeee

**Comment by software-engineer0** [comment]
no.

**Comment by saad977-ai** [comment]
yes ?
 why? 
no?

**Comment by EternityX** [comment]
Please learn how to use StackOverflow or https://www.learncpp.com/
