### ISSUE TITLE
Major crash affecting overall usability

### ISSUE THREAD

**Issue by Pickleses** [EternityX/DEADCELL-CSGO#23]
**Describe the bug**
The game crashes from simply moving the menu after a few minutes with the game open.

**To Reproduce**
Open the game. 
Inject deadcells
wait a few minutes
move the menu
crash

**Comment by alpine971** [comment]
It’s caused by oshgui but I didn’t think it was reproducible consistently

**Comment by EternityX** [comment]
alpine is right, it's been an issue ever since I've started using OSHGui. Adding/debugging simple things turns out to be quite a task with OSHGui.

**Comment by Pickleses** [comment]
The crash is very consistent. If I inject, change nothing from default and wait about 10 minutes (sometimes more, some times less) and move the menu, it will crash every time. The crash seems to be triggered by any menu action (checkboxes, color changer, sliders) including moving the menu.

**Comment by EternityX** [comment]
I've enabled OSHGui's exceptions. Can you try reproducing the steps again and see if you catch any exceptions? Thanks in advance.

If you're unable to test right now, I'll be available tomorrow to do it.

**Comment by Pickleses** [comment]
I have done quite a bit of testing and it seems to be much better. I'm continuing to test.

**Comment by EternityX** [comment]
The changes I did should only make oshgui throw an exception instead of just silently crashing. 
You should attach a debugger if you're able to.

**Comment by Pickleses** [comment]
https://cdn.discordapp.com/attachments/469263314954878978/558716540564930570/unknown.png

Crashed and got this. I'm continuing to investigate and test.

**Comment by alpine971** [comment]
ucrtbase crashes are generally related to text handling, will take a look at this once I’m home.

**Comment by Pickleses** [comment]
https://cdn.discordapp.com/attachments/469263314954878978/558720602761068545/unknown.png

Same test. Just trying to give as much info as possible.

**Comment by Awhkzz** [comment]
Hey so I've tested the new release and I get this error: 
![imagem](https://user-images.githubusercontent.com/41268589/54854424-cc96bd80-4cea-11e9-9889-615e21d96b6a.png). Hope that it helps.

**Comment by alpine971** [comment]
Still happens?, did it crash when you moved the menu?

**Comment by Awhkzz** [comment]
No. Only after like 3-4 seconds that the menu showed up.

**Comment by alpine971** [comment]
That’s super weird, the menu shows up just fine and doesn’t crash on my end

**Comment by Awhkzz** [comment]
Yeah. I'm going to test it again and i'm going to show you every single detail then.

**Comment by Awhkzz** [comment]
Ok, so now it crashed when I moved the menu and I got this 
![imagem](https://user-images.githubusercontent.com/41268589/54855047-c0abfb00-4cec-11e9-971e-ce3a93104847.png). Let me know if you need anything else about the crash

**Comment by alpine971** [comment]
Yeah that’s all we need thank you very much, there’s also a chance it could be related to our Input hook ( I’m not sure ), I’ll look into it, thanks again.

**Comment by Awhkzz** [comment]
No problem men. I'm always ready to help you guys in something that you need.

**Comment by EternityX** [comment]
What Windows SDK version are you using?

You can find it in your project properties.
![img](https://i.imgur.com/GJFoZV2.png)

**Comment by Pickleses** [comment]
![image](https://user-images.githubusercontent.com/43190448/54863023-4772cf00-4d11-11e9-983c-9b3b855bc54d.png)
are you waiting long enough? I can't play more than 15 minutes

**Comment by EternityX** [comment]
> ![image](https://user-images.githubusercontent.com/43190448/54863023-4772cf00-4d11-11e9-983c-9b3b855bc54d.png)
> are you waiting long enough? I can't play more than 15 minutes

Are you waiting in the main menu or in game? I've waited up to 30 minutes each time when testing and haven't received any crashes

**Comment by Awhkzz** [comment]
> 
> 
> I'm unable to reproduce any crashes at this time.
> What version of the Windows SDK are you using?
> 
> You can find it in your project properties.
> ![img](https://camo.githubusercontent.com/159bbabee94b0b214b199c056dc435c66d02ee5f/68747470733a2f2f692e696d6775722e636f6d2f474a466f5a56322e706e67)

these are the properties that I am using 
![imagem](https://user-images.githubusercontent.com/41268589/54864338-dc93b900-4d4d-11e9-8ce0-88d8e840c8e3.png)

**Comment by Awhkzz** [comment]
Hey again. I've tested the newest version and I got this error : 
![imagem](https://user-images.githubusercontent.com/41268589/54868522-32d01e80-4d85-11e9-84ca-55623e7020dc.png)
 and this one too again : 
![imagem](https://user-images.githubusercontent.com/41268589/54868529-572bfb00-4d85-11e9-8546-fe38292da475.png)

**Comment by Awhkzz** [comment]
And now I've just tested injecting while in main menu and I haven't crashed yet. So idk I will continue testing.

**Comment by Pickleses** [comment]
Seems as though that some people are affected by it, but others simply aren't. The crashes that Awhkzz get are precisely the same as the ones I'm receiving. It certainly seems to be related to oshgui

**Comment by EternityX** [comment]
Unfortunately it's pretty difficult to fix it without being able to reproduce it on my end.
Is there a way you can view the assembly instructions at ```0x773551EB``` when the exception is thrown? If it does that could be a huge help.

**Comment by Pickleses** [comment]
![image](https://user-images.githubusercontent.com/43190448/54885063-32e42300-4e46-11e9-8fb6-a7be67e83650.png)

Doing some more testing and investigating

**Comment by alpine971** [comment]
Is that where it threw everytime?

**Comment by EternityX** [comment]
@Pickleses @Awhkzz Have you been able to test 4d4034a?

**Comment by Pickleses** [comment]
I just did quite a bit of testing and I'm still having the exact same crash in the same spot every single time. If there is any info you need, please feel free to ask for it.

**Comment by EternityX** [comment]
I was able to recreate the crash, I'll do some further testing

**Comment by NullFlex** [comment]
I had these same issues, but with ImGui, and it wasn't only when moving the menu (it was more or less random).

**Comment by Pickleses** [comment]
![image](https://user-images.githubusercontent.com/43190448/55122458-160d5100-50cd-11e9-99cb-323c763f7c1e.png)

Still crashes for me. I take the exact repository, unchanged, and compile in debug with debugger attached and it crashes the first time I move the menu. I have noticed however that it happens in game more often. It still crashes in release as well, but not as consistently.

**Comment by EternityX** [comment]
Can you two try disabling multi-core rendering and see if that fixes the issue? It's fixed the issue for me.

**Comment by Pickleses** [comment]
Turning off multicore rendering does prevent it from crashing. I can now investigate other features. Thank you.

**Comment by EternityX** [comment]
Glad to hear that :+1:

**Comment by EternityX** [comment]
Small update: this issue won't be solved until we fix the OSHGui D3D9 renderer or switch to engine drawing.
