### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by x04** [EternityX/DEADCELL-CSGO#31]
It would be nice if one of the project managers could make a Discord server for the project. It'd be easier to collaborate, and this seems like a project I'd be very interested in contributing more to.

**Comment by alpine971** [comment]
Hi, I agree with the idea but it just seems like it will be either dead in couple of days, or continuously getting spammed.

**Comment by x04** [comment]
> Hi, I agree with the idea but it just seems like it will be either dead in couple of days, or continuously getting spammed.

Well I think it would be nice for the projects more relevant contributors, I'd just like an easier way to communicate about the project and knowing how I can most efficiently help with the project.

**Comment by alpine971** [comment]
Sure I guess, let’s just wait on eternity’s input.

**Comment by EternityX** [comment]
Sure.
https://discord.gg/dEMgzUZ
