### ISSUE TITLE
Add antiaim & backtrack

### ISSUE THREAD

**Issue by cold1337** [EternityX/DEADCELL-CSGO#33]
Hello guys ! I have a sugestion.

Go add
- antiaims (only real) or (real+fake/desync)
- backtrack (low/medium/high) or (slide 0 - x ticks) + backtrack correction/adaptive
- resolver/antiaim correction(simple resolving angle feet/body/head) or (desync correction)

**Comment by alpine971** [comment]
There’s a feature request thread present already.
