### ISSUE TITLE
Post any features you'd like here

### ISSUE THREAD

**Issue by EternityX** [EternityX/DEADCELL-CSGO#4]
Just leave a comment on any features you'd like to see, perhaps I or another kind contributor can add it.

**Comment by hvhlord** [comment]
nightmode

**Comment by t9z** [comment]
> nightmode

Already in the cheat, misc tab.

**Comment by decible** [comment]
pvs fix

**Comment by ikeaaa** [comment]
> pvs fix
> glow

Added glow for ya' @decible.

**Comment by estoerik** [comment]
everything is p except from the crashes and a legitbot would be cool

**Comment by atheleon** [comment]
https://github.com/EternityX/DEADCELL-CSGO/issues/4#issuecomment-474544921
In the works. Not sure if I’ll push it or not.

**Comment by proxendev** [comment]
Zeusbot and clantag

**Comment by TheRealMrInnocent** [comment]
Fake duck, Glove changer and Sticker changer, when done Skin changer possibly.

**Comment by Zidjey** [comment]
Fade in and fade out animations on menu opening, closing.

**Comment by Precend0** [comment]
An Inventory changer instead of a Skin changer.

**Comment by viabIe** [comment]
rework anti aim system + possibly add freestanding, 
rework the resolver/improve it, 
if possible tweak/improve ragebot,
add fakewalk
add zeusbot

**Comment by nitrogen69** [comment]
Skinchanger, knifechanger.

**Comment by TXIuTnVsbA** [comment]
add fakeduck(is real fake,not fastduck)
more fakelag option (Ex: Disabled fakelag when i attack or enabled mic )
more anti-aim option
add fakewalk

**Comment by Imforpeace** [comment]
Profile, Inventory, Knife and Glove Changer.

**Comment by Imforpeace** [comment]
Profile, Inventory, Knife and Glove Changer.

**Comment by Fedorito** [comment]
AA Switch in menu, fixed fps indicator when not ingame

**Comment by Fedorito** [comment]
And improve autowall plz

**Comment by TXIuTnVsbA** [comment]
add enemy indicator,when i can't see it in my screen

**Comment by TXIuTnVsbA** [comment]
add backtrack chams

**Comment by AmonKing** [comment]
legitbot

**Comment by butchiboi** [comment]
please update for newest csgo update

**Comment by StornerTV** [comment]
A legitbot would make this the absolute perfect source.

**Comment by alpine971** [comment]
> A legitbot would make this the absolute perfect source.
the cheat is detected since the use of vmt hooking without any modifications to the vac module or whatever, a legitbot would be useless you’ll get banned anyways

**Comment by rafalohaki** [comment]
Auto fire on key

**Comment by Matias2852** [comment]
legitbot

**Comment by TXIuTnVsbA** [comment]
plz,add resolver= =

**Comment by bruteforcehacker** [comment]
maybe add a better antiaim?

**Comment by expectant15** [comment]
Skins

**Comment by rafalohaki** [comment]
> Skins

wtf bro, its dead

**Comment by cheaterbastard** [comment]
Every motherfucker steam reported ... enjoy your ban...

**Comment by EternityX** [comment]
Closing this as the project is no longer being actively updated.
