### ISSUE TITLE
i have the bug after inject DLL

### ISSUE THREAD

**Issue by TXIuTnVsbA** [EternityX/DEADCELL-CSGO#40]
I can build it, inject it, but it something wrong can be stop the client= =

**Comment by TXIuTnVsbA** [comment]
-insecure launch parameter not found.

**Comment by TXIuTnVsbA** [comment]
it going to exit the game when I drag the cheat window

**Comment by TXIuTnVsbA** [comment]
now i know that it is gui Issue,but i dont know how to edit it

**Comment by TXIuTnVsbA** [comment]
>	dc-csgo-debug.dll!std::unique_ptr<OSHGui::Drawing::Renderer,std::default_delete<OSHGui::Drawing::Renderer> >::get() 行 2312	C++

**Comment by TXIuTnVsbA** [comment]
GUI Issue:
>	dc-csgo-debug.dll!OSHGui::Control::OnLocationChanged() 行 667	C++

+		this	0x3a19091c {m_pages={ size=5 } m_tab_control=0x3a369c40 {buttonWidth_=116 selectedIndexChangedEvent_=...} }	OSHGui::Control * {c_main_form}

**Comment by EternityX** [comment]
This is a known issue (#23)
We're trying to find a fix but it's proving difficult

**Comment by TXIuTnVsbA** [comment]
> This is a known issue (#23)
> We're trying to find a fix but it's proving difficult

all right,and, can you update the DEADCELL-SDK ?

**Comment by EternityX** [comment]
Hi,
Try disabling multi-core rendering in your CS:GO video options and report back.

**Comment by TXIuTnVsbA** [comment]
> Hi,
> Try disabling multi-core rendering in your CS:GO video options and report back.

yet,is ok

**Comment by TXIuTnVsbA** [comment]
> Hi,
> Try disabling multi-core rendering in your CS:GO video options and report back.

@EternityX 
Hi, can you help me fix it ?
![bug1](https://raw.githubusercontent.com/TXIuTnVsbA/Test/master/bug1.png)
![bug2](https://raw.githubusercontent.com/TXIuTnVsbA/Test/master/bug2.png)
![bug3](https://raw.githubusercontent.com/TXIuTnVsbA/Test/master/bug3.png)
