### ISSUE TITLE
Menu displayed off-screen/not showing up

### ISSUE THREAD

**Issue by EternityX** [EternityX/DEADCELL-CSGO#42]
Watermark will be displayed in the top left of the screen (instead of the right) and menu will be pushed off-screen.

Pay close attention to the top left of the screen.
![image](https://cdn.discordapp.com/attachments/560554484632387585/560554502965559296/unknown.png) 

I am unable to reproduce this issue for myself, so if anyone else has this issue please post here.

**Comment by abrohIagoksi** [comment]
helo, i have this same issue. when i press insert to open menu, i will not see menu. i dont use the d3d9ex command and i have tried open menu with multicore on and off.

**Comment by kanez0redd** [comment]
same

**Comment by benayau** [comment]
same

**Comment by jdb-jdb** [comment]
For a quick fix to enable you to use Deadcell before it actually gets fixed, I put the whole watermark function(in visuals.cpp)  in a big _**if**_ statement the is false (see photo). In the meantime, I am trying to fix it for real so this won't have to happen in the first place.
![watermark](https://user-images.githubusercontent.com/52080120/62384228-bf67c600-b549-11e9-9af5-bcd6910e1ebd.PNG)

**Comment by jdb-jdb** [comment]
Do you [people with this issue] have dual monitors?

**Comment by shashankmahajan99** [comment]
> Do you [people with this issue] have dual monitors?

no
