### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Fedorito** [EternityX/DEADCELL-CSGO#43]
https://imgur.com/a/z7IVGXr
Crashing when I try to connect to server twice or second time

**Comment by Fedorito** [comment]
Debug says that I triggered a breakpoint(?)

**Comment by alpine971** [comment]
can you try again and show us the whole window while debugging so we take a look at call stack, thanks.

**Comment by Fedorito** [comment]
https://imgur.com/a/jgAUnrR
If you can understand something

**Comment by alpine971** [comment]
> https://imgur.com/a/jgAUnrR
> If you can understand something

alright, thank you for reporting back, we'll look into it.

**Comment by alpine971** [comment]
Hi, this has been fixed in commit 925066a3cca693b8ed0133087d69f98384cb6aeb.
