### ISSUE TITLE
antiaim.yaw overflow

### ISSUE THREAD

**Issue by TXIuTnVsbA** [EternityX/DEADCELL-CSGO#46]
i don't know what is the g_vars.antiaim.jitter;
and  m_input.y  overflow sometime 
I think you need to check the m_input.y data.

**Comment by TXIuTnVsbA** [comment]
and autoscope its dont work
= =i cant fix it

**Comment by EternityX** [comment]
```
i don't know what is the g_vars.antiaim.jitter;
```
It's not implemented yet.

```
and m_input.y overflow sometime
I think you need to check the m_input.y data.
```
I don't understand what you mean by 'overflow'.

```
and autoscope its dont work
```
Autoscope works for me; I just tested it. Are you using Hitchance fail? If you are that means it'll only scope if you are unable to hit them with your specified hitchance value.

**Comment by TXIuTnVsbA** [comment]
> ```
> i don't know what is the g_vars.antiaim.jitter;
> ```
> It's not implemented yet.
> 
> ```
> and m_input.y overflow sometime
> I think you need to check the m_input.y data.
> ```
> I don't understand what you mean by 'overflow'.
> 
> ```
> and autoscope its dont work
> ```
> Autoscope works for me; I just tested it. Are you using Hitchance fail? If you are that means it'll only scope if you are unable to hit them with your specified hitchance value.

the m_input.y must be:
-179.9 < m_input.y < 179.9

but, overflow , 
m_input.y > 179.9 or m_input.y < -179.9

**Comment by EternityX** [comment]
Oh I understand now, I'll check it soon.

**Comment by EternityX** [comment]
Because multi-point is unoptimized.
Turn on Dynamic scanning

**Comment by TXIuTnVsbA** [comment]
> Because multi-point is unoptimized.
> Turn on Dynamic scanning

i turn on it ,but its slow too, maybe my computer is trash.

and , when i change and connect other server, its will exit the game
