### ISSUE TITLE
i cant see menu

### ISSUE THREAD

**Issue by abrohIagoksi** [EternityX/DEADCELL-CSGO#55]
i cant see the menu

**Comment by alpine971** [comment]
hi, can you try to inject in debug mode and see if the console shows up?, look at the printed resolution and compare it to your resolution set in game, get back to us once you've done that :)

**Comment by abrohIagoksi** [comment]
my game crash when i inject the debug

**Comment by alpine971** [comment]
okay that's good, try launching the game in windowed mode then injecting, after that it should be fine when you go into fullscreen
