### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by IceandFireTR** [EternityX/DEADCELL-CSGO#60]
are we injecting dc-csgo-debug.dll?
I injected it in fullscreenwindow too but It crashs please help

**Comment by Orinion** [comment]
try building in Release and injecting DEADCELL-CSGO\build\bin\dc-csgo.dll

**Comment by EternityX** [comment]
I need more information. Attach a debugger.

**Comment by moshater** [comment]
```
dc-csgo-debug.dll!cheat_init(void * arg=0x00000000) Line 84
------------------------------------------------------------------------
dc-csgo-debug.dll!renderer::c_renderer::get_renderer() Line 185

OSHGui::Drawing::Renderer &c_renderer::get_renderer( ) const {
	return get_instance( )->GetRenderer( );
}
------------------------------------------------------------------------
dc-csgo-debug.dll!OSHGui::Application::GetRenderer() Line 99
Drawing::Renderer &Application::GetRenderer() const {
	return *renderer_;
}

```
when in debug seems renderer got nullptr

**Comment by IceandFireTR** [comment]
> in Release

there is not dc-csgo.dll there is dc-csgo-debug.dll

**Comment by TXIuTnVsbA** [comment]
> I need more information. Attach a debugger.

its something wrong,i cant debug it

**Comment by EternityX** [comment]
> > I need more information. Attach a debugger.
> 
> its something wrong,i cant debug it

Again... I need more information other than "something is wrong".

**Comment by daswareinfach** [comment]
same problem f me. i will trying inject dc-csgo.dll. which injector did u use?
