### ISSUE TITLE
Team Shoot

### ISSUE THREAD

**Issue by IceandFireTR** [EternityX/DEADCELL-CSGO#61]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by IceandFireTR** [comment]
When I didnt open teammates It shoots teammates too and esp teammates too

**Comment by EternityX** [comment]
Team check is working fine for me.
Maybe you should actually fill out the bug report instead of leaving the placeholder text.
