### ISSUE TITLE
Assertion Failed Crash Potential Fix

### ISSUE THREAD

**Issue by pOri0n** [EternityX/DEADCELL-CSGO#73]
I had this problem in my paste so i decided to open a forum on uc. That was fixed my problem, maybe works for you too. Check the comments, you'll get what i mean.

https://www.unknowncheats.me/forum/counterstrike-global-offensive/320702-weird-assertion-failed-crash.html

**Comment by EternityX** [comment]
We do use weapon system
https://github.com/EternityX/DEADCELL-CSGO/blob/master/csgo/features/visuals/visuals.cpp#L197
The issue still persists, so we'll eventually just call it in a game thread.

**Comment by EternityX** [comment]
This is fixed.
