### ISSUE TITLE
Desync is incorrect

### ISSUE THREAD

**Issue by emmyie** [EternityX/DEADCELL-CSGO#74]
Your real will be at the fake angle, if you don't switch around the sendpacket stuff also the aa will not work properly with lby breaker

to test your desync simply go on a server, do sv_showlagcompensation 1; sv_lagcompensateself 1;

if the blue hitbox is not lined up with localplayer then you're doing it wrong

**Comment by x04** [comment]
1. You send desync on sendpacket.
2. We don't have an LBY breaker anymore, and if you meant to say you need one to desync, you don't.
3. It's the most proper way to do desync, but it's definitely better than what you're saying to do here.

**Comment by emmyie** [comment]
go on a server and show server hitboxes, you will see that you're doing it wrong
