### ISSUE TITLE
Crashing on fullscreen inject

### ISSUE THREAD

**Issue by k0t-IWNL** [EternityX/DEADCELL-CSGO#78]
Whenever I inject in fullscreen mode, I get a crash. This does not occur in windowed. 
This occurs regardless of injector configuration - load library, manual mapping & multicore rendering all bring the same result.
Unrelated, an unban from the Discord would be strongly appreciated. I did not see the "no support" rule as I accessed the server via this page: https://i.imgur.com/2srlFcD.png . For future reference, I am ilya#7701 on Discord.

**Comment by k0t-IWNL** [comment]
I would like to add that these are my only launch options: "-freq 95 -fullscreen -console -insecure". I am running a 900 series GTX graphics card. I am currently updating my drivers, if this solves the issue I will update this case.

**Comment by EternityX** [comment]
try changing multicore rendering options, if that doesn't work, try launching with -d3d9ex

**Comment by k0t-IWNL** [comment]
As I have originally stated, I have messed around with enabling/disabling multicore rendering. Adding -d3d9ex now means the game doesn't allow me to alt-tab in before crashing. (prior, I would be able to alt-tab into a black screen, before a 'not-responding' message). I appreciate the fast reply, any and all help to solve this is very appreciated.

**Comment by EternityX** [comment]
Have you attempted to attach a debugger? Perhaps the debugger can show you exactly where the crash occurs.

**Comment by k0t-IWNL** [comment]
I have updated my graphics drivers, and the issue persists. I had an issue with building in debug mode, but that has been sorted. I will update this ASAP. Thanks for bearing with me.

**Comment by k0t-IWNL** [comment]
The crash occurs here: https://i.imgur.com/htZQlEU.png
It should bear repeating this only occurs in fullscreen? I am able to inject without issue in windowed.

**Comment by EternityX** [comment]
are you using the latest updates from the repo? Either way, soon we won't be using OSHGui so this issue won't exist anymore.

**Comment by k0t-IWNL** [comment]
Yes, latest update from repo. I have tried rebuilding a fresh and unmodified DLL straight from Github, and the issue is identical. As nice as the menu is, I support moving to imgui, so props for that xx. Any further help is greatly appreciated.

**Comment by e-boi** [comment]
Pull the imgui branch and let us know if it crashes.
There is no GUI other than the default demo window, so I don't recommend using it for purposes other than development.

**Comment by k0t-IWNL** [comment]
2 steps ahead xx
Identical set-up, no crash.

**Comment by e-boi** [comment]
Good to hear, we plan to move away from OSHGUI anyways so stick around when we merge something better into the master branch.
