### ISSUE TITLE
crashing when inject

### ISSUE THREAD

**Issue by Lyricssystem** [EternityX/DEADCELL-CSGO#8]
When injecting this i'm getting crash manual map injector and simple injector

**Comment by Monster24** [comment]
But mine not crashing, but cheat not opening after pressing INSERT :( help plz, which key to open cheat

**Comment by alpine971** [comment]
Use a normal loadlibrary injector without manual map.

**Comment by EternityX** [comment]
do you have -d3d9ex in your CS:GO launch options? If so, remove it and try injecting again.

**Comment by Lyricssystem** [comment]
> do you have -d3d9ex in your CS:GO launch options? If so, remove it and try injecting again.

Thx it is
