### ISSUE TITLE
crashes on injection 

### ISSUE THREAD

**Issue by rudyrdx** [EternityX/DEADCELL-CSGO#88]
**Describe the bug**
after compiling , it crashes when injected , tried injecting with multicore on and off

**Screenshots**
https://gyazo.com/eb6bba53d708c32c7bb8fef3032c1cf9

EDIT:- found this after debugging , how to fix ?

![image](https://user-images.githubusercontent.com/47010058/56346681-52b9fd00-61e0-11e9-9459-145273e5e994.png)

**Comment by k0t-IWNL** [comment]
Interesting, not a dev but this useful. 
What hardware are you running?
Try injecting in fullscreen, fullscreen windowed, and windowed, and lmk what the results are. 
Debug the cheat, and provide a screenshot of where it crashes.

**Comment by EternityX** [comment]
Try disabling Shadow play if you are using an Nvidia graphics card.

**Comment by alpine971** [comment]
it could possibly be your injector, use a loadlibrary injector

**Comment by NexSqaud** [comment]
Try to build cheat w/o AVX support
